FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app
ENV API_BASE_URL="http://api:8001"
EXPOSE 8516

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port", "8516"]
